import os
from pathlib import Path

OPBT_U2A16 = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'#define ENABLE_SVR                         0',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Shipping : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Shipping : 0x00000000 [Modified]',
'    .dw    0x00000000            -- Reset Vector (PE2)         Shipping : 0x00800000 [Modified]',
'    .dw    0x00000000            -- Reset Vector (PE3)         Shipping : 0x00800000 [Modified]',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0x07720000            -- Option byte  0 (OPBT0)     Shipping : 0x3FF30010',
'    .dw    0xF0FB0000            -- Option byte  1 (OPBT1)     Shipping : 0xF0FB0000',
'    .dw    0xFFFFFFFF            -- Option byte  2 (OPBT2)     Shipping : 0x7FFFFFFF [Modified]',
'    .dw    0xF1FFFEFC            -- Option byte  3 (OPBT3)     Shipping : 0xF1FFFEFE [Modified]',
'    .dw    0x0F0F0F0F            -- Option byte  4 (OPBT4)     Shipping : 0x0C0C0C0F [Modified]',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFF0FC3            -- Option byte  6 (OPBT6)     Shipping : 0xFFFF0FC3',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFE            -- Option byte  8 (OPBT8)     Shipping : 0xFFFFFFFE',
'    .dw    0xFFF1FFFF            -- Option byte  9 (OPBT9)     Shipping : 0xFFF1FFFF',
'    .dw    0xF9FD288E            -- Option byte 10 (OPBT10)    Shipping : 0xFBFD288E [Modified]',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Shipping : 0xFFFFFFFF [Modified]',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Shipping : 0xFFFFFFFD [Single map:0xFFFFFFFD Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Shipping : 0xFFFFFFFF',
'    .dw    0x00000192            -- Option byte 14 (OPBT14)    Shipping : 0x00000192',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'',
'#if !ENABLE_SVR',
'    .dw    0x6FFFFFFF            -- Option byte 16 (OPBT16)    Shipping : 0x6FFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte 17 (OPBT17)    Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte 18 (OPBT18)    Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte 19 (OPBT19)    Shipping : 0xFFFFFFFF',
'    .dw    0xF088FF00            -- Option byte 20 (OPBT20)    Shipping : 0xF088FF00',
'    .dw    0x000000CC            -- Option byte 21 (OPBT21)    Shipping : 0x000000CC',
'    .dw    0xC000C000            -- Option byte 22 (OPBT22)    Shipping : 0xC000C000',
'    .dw    0xFFFFC000            -- Option byte 23 (OPBT23)    Shipping : 0xFFFFC000',
'#else',
'    -- 5V',
'    .dw    0xEFFFFF10            -- Option byte 16 (OPBT16)    Shipping : 0x6FFFFFFF',
'    .dw    0xF9AAFCFC            -- Option byte 17 (OPBT17)    Shipping : 0xFFFFFFFF',
'    .dw    0xC4B8C385            -- Option byte 18 (OPBT18)    Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFC3EC            -- Option byte 19 (OPBT19)    Shipping : 0xFFFFFFFF',
'    .dw    0x7088FFEF            -- Option byte 20 (OPBT20)    Shipping : 0xF088FF00',
'    .dw    0x065503CF            -- Option byte 21 (OPBT21)    Shipping : 0x000000CC',
'    .dw    0xFB47FC7A            -- Option byte 22 (OPBT22)    Shipping : 0xC000C000',
'    .dw    0xFFFFFC13            -- Option byte 23 (OPBT23)    Shipping : 0xFFFFC000',
'',
'    -- 3.3V',
'    -- .dw    0xEFFFFF10            -- Option byte 16 (OPBT16)                     Shipping : 0x6FFFFFFF',
'    -- .dw    0xF9AAFCFC            -- Option byte 17 (OPBT17)                     Shipping : 0xFFFFFFFF',
'    -- .dw    0xC736C561            -- Option byte 18 (OPBT18)                     Shipping : 0xFFFFFFFF',
'    -- .dw    0xFFFFC5FE            -- Option byte 19 (OPBT19)                     Shipping : 0xFFFFFFFF',
'    -- .dw    0x7088FFEF            -- Option byte 20 (OPBT20)                     Shipping : 0xF088FF00',
'    -- .dw    0x065503CF            -- Option byte 21 (OPBT21)                     Shipping : 0x000000CC',
'    -- .dw    0xF8C9FA9E            -- Option byte 22 (OPBT22)                     Shipping : 0xC000C000',
'    -- .dw    0xFFFFFA01            -- Option byte 23 (OPBT23)                     Shipping : 0xFFFFC000',
'#endif',
]

OPBT_U2A8 =[]

OPBT_U2A6 = []

OPBT_U2B24E = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Reset : 0x00000000 ',
'    .dw    0x00000000            -- Reset Vector (PE2)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE3)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE4)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE5)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE6)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE7)         Reset : 0x00000000',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Reset : 0x3FE30010',
'    .dw    0x007B0000            -- Option byte  1 (OPBT1)     Reset : 0x007B0000',
'    .dw    0xFFFFFFFF            -- Option byte  2 (OPBT2)     Reset : 0xFFFFFFFF',
'    .dw    0x81FFFEFC            -- Option byte  3 (OPBT3)     Reset : 0x81FF7EFE  [Performance:0x81FFFEFC  Safty:0xA1FFFEFC]',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Reset : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFF3FCF            -- Option byte  6 (OPBT6)     Reset : 0xFFFF3FCF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Reset : 0xFFFFFFFF',
'    .dw    0xB07007FF            -- Option byte  8 (OPBT8)     Reset : 0xF07FFFFF  Changed',
'    .dw    0xF9B0007F            -- Option byte  9 (OPBT9)     Reset : 0xF9B03F7F  [Performance:0xF9B0007F  Safty:0xFDA0007F]',
'    .dw    0xF9FD288E            -- Option byte 10 (OPBT10)    Reset : 0xF9FD288E',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Reset : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Reset : 0xFFFFFFFD  [Single map:0xFFFFFFFD   Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Reset : 0xFFFFFFFF',
'    .dw    0xFDBC8994            -- Option byte 14 (OPBT14)    Reset : 0xFDBC8994',
'    .dw    0xFDBC8F94            -- Option byte 15 (OPBT15)    Reset : 0xFDBC8F94',
'    .dw    0x74FFFF10            -- Option byte 16 (OPBT16)    Reset : 0x74FFFF10',
'    .dw    0xF9AAFCFC            -- Option byte 17 (OPBT17)    Reset : 0xF9AAFCFC',
'    .dw    0xC26BC1CE            -- Option byte 18 (OPBT18)    Reset : 0xC26BC1CE',
'    .dw    0xFFFFC203            -- Option byte 19 (OPBT19)    Reset : 0xFFFFC203',
'    .dw    0xCB88FFEF            -- Option byte 20 (OPBT20)    Reset : 0xCB88FFEF',
'    .dw    0x065503CF            -- Option byte 21 (OPBT21)    Reset : 0x065503CF',
'    .dw    0xFD94FE31            -- Option byte 22 (OPBT22)    Reset : 0xFD94FE31',
'    .dw    0xFFFFFDFC            -- Option byte 23 (OPBT23)    Reset : 0xFFFFFDFC',
'    .dw    0xFFFFF9B0            -- Option byte 24 (OPBT24)    Reset : 0xFFFFFFFC  [REDUN OPBT9][Performance:0xFFFFF9B0  Safty:0xFFFFFDA0]',
'    .dw    0xFFC0F3FF            -- Option byte 25 (OPBT25)    Reset : 0xFFC0F3FF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Reset : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Reset : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Option byte 28 (OPBT28)    Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0x8104C9FF            -- Option byte 36 (OPBT36)    Reset : 0x8184C9FF  [REDUN OPBT3][Performance:0x8104C9FF  Safty:0xA104C9FF]',
'    .dw    0x02EFFF55            -- Option byte 37 (OPBT37)    Reset : 0x02EFFF55',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0xFF00FCFF            -- Option byte 40 (OPBT40)    Reset : 0xFF00FCFF',
'    .dw    0xFFFFFFFF            -- Option byte 41 (OPBT41)    Reset : 0xFFFFFFFF',
'    .dw    0xF8FFFFFF            -- Option byte 42 (OPBT42)    Reset : 0xF8FFFFFF',
'    .dw    0x2B01B824            -- Option byte 43 (OPBT43)    Reset : 0x2B01B824',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
]


OPBT_U2B16E = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Reset : 0x00000000 ',
'    .dw    0x00000000            -- Reset Vector (PE2)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE3)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE4)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE5)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE6)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE7)         Reset : 0x00000000',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Reset : 0x3FE30010',
'    .dw    0x007B0000            -- Option byte  1 (OPBT1)     Reset : 0x007B0000',
'    .dw    0xFFFFFFFF            -- Option byte  2 (OPBT2)     Reset : 0xFFFFFFFF',
'    .dw    0x81FFFEFC            -- Option byte  3 (OPBT3)     Reset : 0x81FF7EFE  [Performance:0x81FFFEFC  Safty:0xA1FFFEFC]',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Reset : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFF3FCF            -- Option byte  6 (OPBT6)     Reset : 0xFFFF3FCF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Reset : 0xFFFFFFFF',
'    .dw    0xB07007FF            -- Option byte  8 (OPBT8)     Reset : 0xF07FFFFF  Changed',
'    .dw    0xF9B0007F            -- Option byte  9 (OPBT9)     Reset : 0xF9B03F7F  [Performance:0xF9B0007F  Safty:0xFDA0007F]',
'    .dw    0xF9FD288E            -- Option byte 10 (OPBT10)    Reset : 0xF9FD288E',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Reset : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Reset : 0xFFFFFFFD  [Single map:0xFFFFFFFD   Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Reset : 0xFFFFFFFF',
'    .dw    0xFDBC8994            -- Option byte 14 (OPBT14)    Reset : 0xFDBC8994',
'    .dw    0xFDBC8F94            -- Option byte 15 (OPBT15)    Reset : 0xFDBC8F94',
'    .dw    0x74FFFF10            -- Option byte 16 (OPBT16)    Reset : 0x74FFFF10',
'    .dw    0xF9AAFCFC            -- Option byte 17 (OPBT17)    Reset : 0xF9AAFCFC',
'    .dw    0xC26BC1CE            -- Option byte 18 (OPBT18)    Reset : 0xC26BC1CE',
'    .dw    0xFFFFC203            -- Option byte 19 (OPBT19)    Reset : 0xFFFFC203',
'    .dw    0xCB88FFEF            -- Option byte 20 (OPBT20)    Reset : 0xCB88FFEF',
'    .dw    0x065503CF            -- Option byte 21 (OPBT21)    Reset : 0x065503CF',
'    .dw    0xFD94FE31            -- Option byte 22 (OPBT22)    Reset : 0xFD94FE31',
'    .dw    0xFFFFFDFC            -- Option byte 23 (OPBT23)    Reset : 0xFFFFFDFC',
'    .dw    0xFFFFF9B0            -- Option byte 24 (OPBT24)    Reset : 0xFFFFFFFC  [REDUN OPBT9][Performance:0xFFFFF9B0  Safty:0xFFFFFDA0]',
'    .dw    0xFFC0F3FF            -- Option byte 25 (OPBT25)    Reset : 0xFFC0F3FF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Reset : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Reset : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Option byte 28 (OPBT28)    Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0x8104C9FF            -- Option byte 36 (OPBT36)    Reset : 0x8184C9FF  [REDUN OPBT3][Performance:0x8104C9FF  Safty:0xA104C9FF]',
'    .dw    0x02EFFF55            -- Option byte 37 (OPBT37)    Reset : 0x02EFFF55',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0xFF00FCFF            -- Option byte 40 (OPBT40)    Reset : 0xFF00FCFF',
'    .dw    0xFFFFFFFF            -- Option byte 41 (OPBT41)    Reset : 0xFFFFFFFF',
'    .dw    0xF8FFFFFF            -- Option byte 42 (OPBT42)    Reset : 0xF8FFFFFF',
'    .dw    0x2B01B824            -- Option byte 43 (OPBT43)    Reset : 0x2B01B824',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
]

OPBT_U2B12E = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Reset : 0x00000000 ',
'    .dw    0x00000000            -- Reset Vector (PE2)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE3)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE4)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE5)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE6)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE7)         Reset : 0x00000000',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Reset : 0x3FE30010',
'    .dw    0x007B0000            -- Option byte  1 (OPBT1)     Reset : 0x007B0000',
'    .dw    0xFFFFFFFF            -- Option byte  2 (OPBT2)     Reset : 0xFFFFFFFF',
'    .dw    0xBDFFFEFC            -- Option byte  3 (OPBT3)     Reset : 0xBDFF7EFE',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Reset : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFF3FCF            -- Option byte  6 (OPBT6)     Reset : 0xFFFF3FCF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Reset : 0xFFFFFFFF',
'    .dw    0xB07007FF            -- Option byte  8 (OPBT8)     Reset : 0xF07FF7FF  Changed',
'    .dw    0xF9BC007F            -- Option byte  9 (OPBT9)     Reset : 0xF9BC0F7F  [Performance:0xF9BC007F  Safty:0xFBB8007F]',
'    .dw    0xF9FD288E            -- Option byte 10 (OPBT10)    Reset : 0xF9FD288E',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Reset : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Reset : 0xFFFFFFFD  [Single map:0xFFFFFFFD   Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Reset : 0xFFFFFFFF',
'    .dw    0xFDBC8994            -- Option byte 14 (OPBT14)    Reset : 0xFDBC8994',
'    .dw    0xFDBC8F94            -- Option byte 15 (OPBT15)    Reset : 0xFDBC8F94',
'    .dw    0x74FFFF10            -- Option byte 16 (OPBT16)    Reset : 0x74FFFF10',
'    .dw    0xF9AAFCFC            -- Option byte 17 (OPBT17)    Reset : 0xF9AAFCFC',
'    .dw    0xC26BC1CE            -- Option byte 18 (OPBT18)    Reset : 0xC26BC1CE',
'    .dw    0xFFFFC203            -- Option byte 19 (OPBT19)    Reset : 0xFFFFC203',
'    .dw    0xCB88FFEF            -- Option byte 20 (OPBT20)    Reset : 0xCB88FFEF',
'    .dw    0x065503CF            -- Option byte 21 (OPBT21)    Reset : 0x065503CF',
'    .dw    0xFD94FE31            -- Option byte 22 (OPBT22)    Reset : 0xFD94FE31',
'    .dw    0xFFFFFDFC            -- Option byte 23 (OPBT23)    Reset : 0xFFFFFDFC',
'    .dw    0xFFFFF9BC            -- Option byte 24 (OPBT24)    Reset : 0xFFFFFFFC  [REDUN OPBT9][Performance:0xFFFFF9BC  Safty:0xFFFFFDA0]',
'    .dw    0xFFC0F3FF            -- Option byte 25 (OPBT25)    Reset : 0xFFC0F3FF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Reset : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Reset : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Option byte 28 (OPBT28)    Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0x8104C9FF            -- Option byte 36 (OPBT36)    Reset : 0x8184C9FF  [REDUN OPBT3][Performance:0x8104C9FF  Safty:0xA104C9FF]',
'    .dw    0x02EFFF55            -- Option byte 37 (OPBT37)    Reset : 0x02EFFF55',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0xFF00FCFF            -- Option byte 40 (OPBT40)    Reset : 0xFF00FCFF',
'    .dw    0xFFFFFFFF            -- Option byte 41 (OPBT41)    Reset : 0xFFFFFFFF',
'    .dw    0xF8FFFFFF            -- Option byte 42 (OPBT42)    Reset : 0xF8FFFFFF',
'    .dw    0x2B01B824            -- Option byte 43 (OPBT43)    Reset : 0x2B01B824',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
]

OPBT_U2B6E = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Reset : 0x00000000 ',
'    .dw    0x00000000            -- Reset Vector (PE2)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE3)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE4)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE5)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE6)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE7)         Reset : 0x00000000',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Reset : 0x3FE30010',
'    .dw    0x007B0000            -- Option byte  1 (OPBT1)     Reset : 0x007B0000',
'    .dw    0xFFFFFFFF            -- Option byte  2 (OPBT2)     Reset : 0xFFFFFFFF',
'    .dw    0xBDFFFEFC            -- Option byte  3 (OPBT3)     Reset : 0xBDFF7EFE',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Reset : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFF3FCF            -- Option byte  6 (OPBT6)     Reset : 0xFFFF3FCF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Reset : 0xFFFFFFFF',
'    .dw    0xB07007FF            -- Option byte  8 (OPBT8)     Reset : 0xF07FFFFF  Changed',
'    .dw    0xBDBC7CFE            -- Option byte  9 (OPBT9)     Reset : 0xBDFF7EFE  Changed',
'    .dw    0xF9FD288E            -- Option byte 10 (OPBT10)    Reset : 0xF9FD288E',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Reset : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Reset : 0xFFFFFFFD  [Single map:0xFFFFFFFD   Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Reset : 0xFFFFFFFF',
'    .dw    0xFDBC8994            -- Option byte 14 (OPBT14)    Reset : 0xFDBC8994',
'    .dw    0xFDBC8F94            -- Option byte 15 (OPBT15)    Reset : 0xFDBC8F94',
'    .dw    0x74FFFF10            -- Option byte 16 (OPBT16)    Reset : 0x74FFFF10',
'    .dw    0xF9AAFCFC            -- Option byte 17 (OPBT17)    Reset : 0xF9AAFCFC',
'    .dw    0xC26BC1CE            -- Option byte 18 (OPBT18)    Reset : 0xC26BC1CE',
'    .dw    0xFFFFC203            -- Option byte 19 (OPBT19)    Reset : 0xFFFFC203',
'    .dw    0xCB88FFEF            -- Option byte 20 (OPBT20)    Reset : 0xCB88FFEF',
'    .dw    0x065503CF            -- Option byte 21 (OPBT21)    Reset : 0x065503CF',
'    .dw    0xFD94FE31            -- Option byte 22 (OPBT22)    Reset : 0xFD94FE31',
'    .dw    0xFFFFFDFC            -- Option byte 23 (OPBT23)    Reset : 0xFFFFFDFC',
'    .dw    0xFFFFF9BC            -- Option byte 24 (OPBT24)    Reset : 0xFFFFFFFC  [REDUN OPBT9]',
'    .dw    0xFFC0F3FF            -- Option byte 25 (OPBT25)    Reset : 0xFFC0F3FF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Reset : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Reset : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Option byte 28 (OPBT28)    Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xBD04C9FF            -- Option byte 36 (OPBT36)    Reset : 0xBD84C9FF  [REDUN OPBT3]',
'    .dw    0x02EFFF55            -- Option byte 37 (OPBT37)    Reset : 0x02EFFF55',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0x00000000            -- Reserved                   Reset : 0x00000000',
'    .dw    0xFF00FCFF            -- Option byte 40 (OPBT40)    Reset : 0xFF00FCFF',
'    .dw    0xFFFFFFFF            -- Option byte 41 (OPBT41)    Reset : 0xFFFFFFFF',
'    .dw    0xF8FFFFFF            -- Option byte 42 (OPBT42)    Reset : 0xF8FFFFFF',
'    .dw    0x2B01B824            -- Option byte 43 (OPBT43)    Reset : 0x2B01B824',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
]


OPBT_U2B10 = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Reset : 0x00000000 ',
'    .dw    0x00000000            -- Reset Vector (PE2)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE3)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE4)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE5)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE6)         Reset : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE7)         Reset : 0x00000000',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Reset : 0x3FE30010',
'    .dw    0x007B0000            -- Option byte  1 (OPBT1)     Reset : 0x007B0000',
'    .dw    0xFFFFFFFF            -- Option byte  2 (OPBT2)     Reset : 0xFFFFFFFF',
'    .dw    0xF1FB7EFC            -- Option byte  3 (OPBT3)     Reset : 0xF9FB7EFE  Changed',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Reset : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFF3FCF            -- Option byte  6 (OPBT6)     Reset : 0xFFFF3FCF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Reset : 0xFFFFFFFF',
'    .dw    0xE04FF3F7            -- Option byte  8 (OPBT8)     Reset : 0xE04FFFFF  Changed',
'    .dw    0xFFFC0F7F            -- Option byte  9 (OPBT9)     Reset : 0xFFFC077F  Changed',
'    .dw    0xF9FD288E            -- Option byte 10 (OPBT10)    Reset : 0xF9FD288E',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Reset : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Reset : 0xFFFFFFFD [Single map:0xFFFFFFFD Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Reset : 0xFFFFFFFF',
'    .dw    0xFF7F8004            -- Option byte 14 (OPBT14)    Reset : 0xFF7F8004',
'    .dw    0xFF7F0004            -- Option byte 15 (OPBT15)    Reset : 0xFF7F0004',
'    .dw    0x74FFFF10            -- Option byte 16 (OPBT16)    Reset : 0x74FFFF10',
'    .dw    0xF9AAFCFC            -- Option byte 17 (OPBT17)    Reset : 0xF9AAFCFC',
'    .dw    0xC26BC1CE            -- Option byte 18 (OPBT18)    Reset : 0xC26BC1CE',
'    .dw    0xFFFFC203            -- Option byte 19 (OPBT19)    Reset : 0xFFFFC203',
'    .dw    0xCB88FFEF            -- Option byte 20 (OPBT20)    Reset : 0xCB88FFEF',
'    .dw    0x065503CF            -- Option byte 21 (OPBT21)    Reset : 0x065503CF',
'    .dw    0xFD94FE31            -- Option byte 22 (OPBT22)    Reset : 0xFD94FE31',
'    .dw    0xFFFFFDFC            -- Option byte 23 (OPBT23)    Reset : 0xFFFFFDFC',
'    .dw    0xFFFFFFF0            -- Option byte 24 (OPBT24)    Reset : 0xFFFFFFFC',
'    .dw    0xFFC0F3FF            -- Option byte 25 (OPBT25)    Reset : 0xFFC0F3FF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Reset : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Reset : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Option byte 28 (OPBT28)    Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xF104C8FF            -- Option byte 36 (OPBT36)    Reset : 0xF984C8FF  changed',
'    .dw    0x02EFFF55            -- Option byte 37 (OPBT37)    Reset : 0x02EFFF55',
'    .dw    0x00000000            -- Option byte 38 (OPBT38)    Reset : 0x00000000',
'    .dw    0x00000000            -- Option byte 39 (OPBT39)    Reset : 0x00000000',
'    .dw    0xFF00FCFF            -- Option byte 40 (OPBT40)    Reset : 0xFF00FCFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Reset : 0xFFFFFFFF',
]


OPBT_U2B6 = []



OPBT_U2C8 = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Shipping : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Shipping : 0x00000000 [Modified]',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Shipping : 0x3FF30010 [Modified]',
'    .dw    0xFC7B0000            -- Option byte  1 (OPBT1)     Shipping : 0xFC7B0000',
'    .dw    0xFFFFFFFF            -- Reserved2                  Shipping : 0xFFFFFFFF',
'    .dw    0xFDFFFEFC            -- Option byte  3 (OPBT3)     Shipping : 0xFDFF7EFE [Modified]',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Shipping : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved5                  Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte  6 (OPBT6)     Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Shipping : 0xFFFFFFFF',
'    .dw    0xF97FFFFF            -- Option byte  8 (OPBT8)     Shipping : 0xF97FFFFF',
'    .dw    0xFFFCFFFF            -- Option byte  9 (OPBT9)     Shipping : 0xFFFCFFFF',
'    .dw    0xFAFD288A            -- Option byte 10 (OPBT10)    Shipping : 0xFAFD288A',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Shipping : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Shipping : 0xFFFFFFFD [Single map:0xFFFFFFFD Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved14                 Shipping : 0xFFFFFFFF',
'    .dw    0xFDBC8F94            -- Option byte 15 (OPBT15)    Shipping : U2C8-EVA,U2C8: FDBC 8F94H; U2C4,U2C2: FFFF 8E0CH',
'    .dw    0xFFFFFFFF            -- Reserved16                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved17                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved18                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved19                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved20                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved21                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved22                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved23                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFC            -- Option byte 24 (OPBT24)    Shipping : 0xFFFFFFFC',
'    .dw    0xFFFFFFFF            -- Reserved25                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Shipping : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Shipping : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Reserved28                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved29                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved30                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved31                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved32                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved33                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved34                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved35                 Shipping : 0xFFFFFFFF',
'    .dw    0xFDFFFFFF            -- Option byte 36 (OPBT36)    Shipping : 0xFDFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved37                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved38                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved39                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved40                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved41                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved42                 Shipping : 0xFFFFFFFF',
'    .dw    0x2B01B824            -- Option byte 43 (OPBT43)    Shipping : 0x2B01B824',
'    .dw    0xFFFFFFFF            -- Reserved 0450              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0454              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0458              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 045C              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0460              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0464              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0468              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 046C              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0470              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0474              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0478              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 047C              Shipping : 0xFFFFFFFF',
]

OPBT_U2C4 = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Shipping : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Shipping : 0x00000000 [Modified]',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Shipping : 0x3FF30010 [Modified]',
'    .dw    0xFC7B0000            -- Option byte  1 (OPBT1)     Shipping : 0xFC7B0000',
'    .dw    0xFFFFFFFF            -- Reserved2                  Shipping : 0xFFFFFFFF',
'    .dw    0xFDFFFEFC            -- Option byte  3 (OPBT3)     Shipping : 0xFDFF7EFE [Modified]',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Shipping : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved5                  Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte  6 (OPBT6)     Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Shipping : 0xFFFFFFFF',
'    .dw    0xF97FFFFF            -- Option byte  8 (OPBT8)     Shipping : 0xF97FFFFF',
'    .dw    0xFFFCFFFF            -- Option byte  9 (OPBT9)     Shipping : 0xFFFCFFFF',
'    .dw    0xFAFD288A            -- Option byte 10 (OPBT10)    Shipping : 0xFAFD288A',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Shipping : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Shipping : 0xFFFFFFFD [Single map:0xFFFFFFFD Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved14                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFF8E0C            -- Option byte 15 (OPBT15)    Shipping : U2C8-EVA,U2C8: FDBC 8F94H; U2C4,U2C2: FFFF 8E0CH',
'    .dw    0xFFFFFFFF            -- Reserved16                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved17                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved18                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved19                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved20                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved21                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved22                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved23                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFC            -- Option byte 24 (OPBT24)    Shipping : 0xFFFFFFFC',
'    .dw    0xFFFFFFFF            -- Reserved25                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Shipping : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Shipping : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Reserved28                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved29                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved30                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved31                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved32                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved33                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved34                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved35                 Shipping : 0xFFFFFFFF',
'    .dw    0xFDFFFFFF            -- Option byte 36 (OPBT36)    Shipping : 0xFDFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved37                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved38                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved39                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved40                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved41                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved42                 Shipping : 0xFFFFFFFF',
'    .dw    0x2B01B824            -- Option byte 43 (OPBT43)    Shipping : 0x2B01B824',
'    .dw    0xFFFFFFFF            -- Reserved 0450              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0454              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0458              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 045C              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0460              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0464              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0468              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 046C              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0470              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0474              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0478              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 047C              Shipping : 0xFFFFFFFF',
]

OPBT_U2C2 = [
'/*1. Modify the Option Byte you want to modify in the "set_csa.850" file and save*/',
'/*2. Compile the project and connect the target*/',
'/*3. Enter "target FLASHEXTRA config1 on" in the 850eserv2 console*/',
'/*4. Enter "target FLASHEXTRA" to check whether to enable access to the Option Byte area (optional)*/',
'/*5. Click Download to download the program, and the option Byte flashing has been completed after downloading*/',
'',
'------------------------------------------------------------------------------',
'--    set Configuration Setting Area (Option Bytes, Reset Vector)',
'------------------------------------------------------------------------------',
'    .section "CSA_SECTION", const',
'    .align    4',
'    .dw    0x00000000            -- Reset Vector (PE0)         Shipping : 0x00000000',
'    .dw    0x00000000            -- Reset Vector (PE1)         Shipping : 0x00000000 [Modified]',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved                   Shipping : 0xFFFFFFFF',
'    .dw    0x3FF30010            -- Option byte  0 (OPBT0)     Shipping : 0x3FF30010 [Modified]',
'    .dw    0xFC7B0000            -- Option byte  1 (OPBT1)     Shipping : 0xFC7B0000',
'    .dw    0xFFFFFFFF            -- Reserved2                  Shipping : 0xFFFFFFFF',
'    .dw    0xFDFFFEFC            -- Option byte  3 (OPBT3)     Shipping : 0xFDFF7EFE [Modified]',
'    .dw    0x0C0C0C0B            -- Option byte  4 (OPBT4)     Shipping : 0x0C0C0C0B',
'    .dw    0xFFFFFFFF            -- Reserved5                  Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte  6 (OPBT6)     Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Option byte  7 (OPBT7)     Shipping : 0xFFFFFFFF',
'    .dw    0xF97FFFFF            -- Option byte  8 (OPBT8)     Shipping : 0xF97FFFFF',
'    .dw    0xFFFCFFFF            -- Option byte  9 (OPBT9)     Shipping : 0xFFFCFFFF',
'    .dw    0xFAFD288A            -- Option byte 10 (OPBT10)    Shipping : 0xFAFD288A',
'    .dw    0xEFFFFFFF            -- Option byte 11 (OPBT11)    Shipping : 0xEFFFFFFF',
'    .dw    0xFFFFFFFD            -- Option byte 12 (OPBT12)    Shipping : 0xFFFFFFFD [Single map:0xFFFFFFFD Double map:0xFFFFFFFC]',
'    .dw    0xFFFFFFFF            -- Option byte 13 (OPBT13)    Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved14                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFF8E0C            -- Option byte 15 (OPBT15)    Shipping : U2C8-EVA,U2C8: FDBC 8F94H; U2C4,U2C2: FFFF 8E0CH',
'    .dw    0xFFFFFFFF            -- Reserved16                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved17                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved18                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved19                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved20                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved21                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved22                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved23                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFC            -- Option byte 24 (OPBT24)    Shipping : 0xFFFFFFFC',
'    .dw    0xFFFFFFFF            -- Reserved25                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFF0010            -- Option byte 26 (OPBT26)    Shipping : 0xFFFF0010',
'    .dw    0xFFFF0000            -- Option byte 27 (OPBT27)    Shipping : 0xFFFF0000',
'    .dw    0xFFFFFFFF            -- Reserved28                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved29                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved30                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved31                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved32                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved33                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved34                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved35                 Shipping : 0xFFFFFFFF',
'    .dw    0xFDFFFFFF            -- Option byte 36 (OPBT36)    Shipping : 0xFDFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved37                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved38                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved39                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved40                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved41                 Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved42                 Shipping : 0xFFFFFFFF',
'    .dw    0x2B01B824            -- Option byte 43 (OPBT43)    Shipping : 0x2B01B824',
'    .dw    0xFFFFFFFF            -- Reserved 0450              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0454              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0458              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 045C              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0460              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0464              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0468              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 046C              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0470              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0474              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 0478              Shipping : 0xFFFFFFFF',
'    .dw    0xFFFFFFFF            -- Reserved 047C              Shipping : 0xFFFFFFFF',
]


def set_CSA(mcu_series):

    # 获取当前目录的绝对路径
    current_path = os.getcwd()

    # 构造文件路径
    file_850 = os.path.join(current_path, "code", "startup", "set_csa.850")
    file_txt = os.path.join(current_path, "code", "startup", "set_csa.txt")

    # 检查并删除旧文件
    if os.path.exists(file_850):
        try:
            os.remove(file_850)
        except Exception as e:
            print(f"  删除set_csa.850文件失败: {e}")
            return False

    # 新建并写入TXT文件
    try:
        with open(file_txt, 'w', encoding='utf-8') as f:

            if mcu_series == 'U2A16':
                for opbt in OPBT_U2A16:
                    f.write(opbt + '\n')

            if mcu_series == 'U2A8':
                for opbt in OPBT_U2A8:
                    f.write(opbt + '\n')
                        
            if mcu_series == 'U2A6':
                for opbt in OPBT_U2A6:
                    f.write(opbt + '\n')

            if mcu_series == 'U2B24-E':
                for opbt in OPBT_U2B24E:
                    f.write(opbt + '\n')

            if mcu_series == 'U2B16-E':
                for opbt in OPBT_U2B16E:
                    f.write(opbt + '\n')

            if mcu_series == 'U2B12-E':
                for opbt in OPBT_U2B12E:
                    f.write(opbt + '\n')

            if mcu_series == 'U2B6-E':
                for opbt in OPBT_U2B6E:
                    f.write(opbt + '\n')
                    
            if mcu_series == 'U2B10':
                for opbt in OPBT_U2B10:
                    f.write(opbt + '\n')
                        
            if mcu_series == 'U2B6':
                for opbt in OPBT_U2B6:
                    f.write(opbt + '\n')
            
            if mcu_series == 'U2C8':
                for opbt in OPBT_U2C8:
                    f.write(opbt + '\n')

            if mcu_series == 'U2C4':
                for opbt in OPBT_U2C4:
                    f.write(opbt + '\n')

            if mcu_series == 'U2C2':
                for opbt in OPBT_U2C2:
                    f.write(opbt + '\n')

    except Exception as e:
        print(f"  写入set_csa.850文件失败: {e}")
        return False

    # 修改后缀为.850
    try:
        os.rename(file_txt, file_850)
        return True
    except Exception as e:
        print(f"  修改set_csa.850后缀失败: {e}")
        return False



